### ISSUE TITLE
Consumir refeições

### ISSUE THREAD

**Issue by NnoukK** [NnoukK/shiny-octo-chainsaw#13]
Basta pedir um numero de utilizador, e verificar se esse utilizador tem alguma refeicao para o currentDate() se tiver eliminar essa refeição ao inserir isto:

refeicao ref;

ref.numero = INT_MIN;

e substituir na posição do array que contem essa refeição...

**Comment by NnoukK** [comment]
Depois da conclusão disto irei fazer mais um pull para o master!!!

**Comment by V3loz4** [comment]
DONE!!!!!!!

**Comment by NnoukK** [comment]
Good Job
